### ISSUE TITLE
Terminal fails to build

### ISSUE THREAD

**Issue by jbrannst** [osevg/workshopper-content#106]
On RHPDS

Build logs for Terminal-app-base-1

Cloning "https://github.com/openshift-evangelists/workshop-base-image.git " ...
--
  | Commit:	0ca5ddf88577ae09fa174ee9746d85e0768bf128 (Make odo version a parameter.)
  | Author:	Graham Dumpleton <Graham.Dumpleton@gmail.com>
  | Date:	Thu Sep 27 19:46:02 2018 +0200
  | Replaced Dockerfile FROM image centos/s2i-base-centos7:latest
  |  
  | Pulling image centos/s2i-base-centos7 ...
  | Pulled 2/5 layers, 45% complete
  | Pulled 3/5 layers, 60% complete
  | Pulled 4/5 layers, 80% complete
  | Pulled 5/5 layers, 100% complete
  | Extracting
  | Step 1/28 : FROM centos/s2i-base-centos7
  | ---> a98d059676a7
  | Step 2/28 : RUN HOME=/root &&     INSTALL_PKGS="nano python-devel" &&     yum install -y centos-release-scl &&     yum -y --setopt=tsflags=nodocs install --enablerepo=centosplus $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     yum -y clean all --enablerepo='*'
  | ---> Running in cc3d07cf3ffe
  |  
  | Loaded plugins: fastestmirror, ovl
  | Determining fastest mirrors
  | * base: mirror.fra10.de.leaseweb.net
  | * extras: mirror.fra10.de.leaseweb.net
  | * updates: mirror.infonline.de
  | Package centos-release-scl-2-2.el7.centos.noarch already installed and latest version
  | Nothing to do
  | Loaded plugins: fastestmirror, ovl
  | Loading mirror speeds from cached hostfile
  | * base: mirror.fra10.de.leaseweb.net
  | * centosplus: mirror.fra10.de.leaseweb.net
  | * extras: mirror.fra10.de.leaseweb.net
  | * updates: mirror.infonline.de
  | Resolving Dependencies
  | --> Running transaction check
  | ---> Package nano.x86_64 0:2.3.1-10.el7 will be installed
  | ---> Package python-devel.x86_64 0:2.7.5-76.el7 will be installed
  | --> Finished Dependency Resolution
  |  
  | Dependencies Resolved
  |  
  | ================================================================================
  | Package              Arch           Version                 Repository    Size
  | ================================================================================
  | Installing:
  | nano                 x86_64         2.3.1-10.el7            base         440 k
  | python-devel         x86_64         2.7.5-76.el7            base         398 k
  |  
  | Transaction Summary
  | ================================================================================
  | Install  2 Packages
  |  
  | Total download size: 837 k
  | Installed size: 2.7 M
  | Downloading packages:
  | --------------------------------------------------------------------------------
  | Total                                              3.1 MB/s \| 837 kB  00:00
  | Running transaction check
  | Running transaction test
  | Transaction test succeeded
  | Running transaction
  | Installing : python-devel-2.7.5-76.el7.x86_64                             1/2
  | Installing : nano-2.3.1-10.el7.x86_64                                     2/2
  | Verifying  : nano-2.3.1-10.el7.x86_64                                     1/2
  | Verifying  : python-devel-2.7.5-76.el7.x86_64                             2/2
  |  
  | Installed:
  | nano.x86_64 0:2.3.1-10.el7         python-devel.x86_64 0:2.7.5-76.el7
  |  
  | Complete!
  | Loaded plugins: fastestmirror, ovl
  | Cleaning repos: C7.0.1406-base C7.0.1406-centosplus C7.0.1406-extras
  | : C7.0.1406-fasttrack C7.0.1406-updates C7.1.1503-base
  | : C7.1.1503-centosplus C7.1.1503-extras C7.1.1503-fasttrack
  | : C7.1.1503-updates C7.2.1511-base C7.2.1511-centosplus
  | : C7.2.1511-extras C7.2.1511-fasttrack C7.2.1511-updates
  | : C7.3.1611-base C7.3.1611-centosplus C7.3.1611-extras
  | : C7.3.1611-fasttrack C7.3.1611-updates C7.4.1708-base
  | : C7.4.1708-centosplus C7.4.1708-extras C7.4.1708-fasttrack
  | : C7.4.1708-updates C7.5.1804-base C7.5.1804-centosplus
  | : C7.5.1804-extras C7.5.1804-fasttrack C7.5.1804-updates base
  | : base-debuginfo base-source c7-media centos-sclo-rh
  | : centos-sclo-rh-debuginfo centos-sclo-rh-source
  | : centos-sclo-rh-testing centos-sclo-sclo
  | : centos-sclo-sclo-debuginfo centos-sclo-sclo-source
  | : centos-sclo-sclo-testing centosplus centosplus-source cr extras
  | : extras-source fasttrack updates updates-source
  | Cleaning up list of fastest mirrors
  | ---> 1824559f6701
  | Removing intermediate container cc3d07cf3ffe
  | Step 3/28 : ARG OC_VERSION=3.10.41
  | ---> Running in 132342c7581e
  | ---> ce5e35a36de0
  | Removing intermediate container 132342c7581e
  | Step 4/28 : ARG ODO_VERSION=0.0.12
  | ---> Running in 6ebb22fc94d2
  | ---> 71b2a9891b53
  | Removing intermediate container 6ebb22fc94d2
  | Step 5/28 : RUN curl -s -o /tmp/oc.tar.gz "https://mirror.openshift.com/pub/openshift-v3/clients/$OC_VERSION/linux/oc.tar.gz " &&     tar -C /usr/local/bin -zxvf /tmp/oc.tar.gz oc &&     rm /tmp/oc.tar.gz &&     curl -sL -o /usr/local/bin/odo https://github.com/redhat-developer/odo/releases/download/v$ODO_VERSION/odo-linux-amd64  &&     chmod +x /usr/local/bin/odo
  | ---> Running in 1cc7d9396cd2
  |  
  | oc
  | ---> f94b8939bc23
  | Removing intermediate container 1cc7d9396cd2
  | Step 6/28 : ARG KUBECTL_VERSION=1.10.0
  | ---> Running in 0a9e22b13162
  | ---> 517df05a0599
  | Removing intermediate container 0a9e22b13162
  | Step 7/28 : RUN curl -sL -o /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v$KUBECTL_VERSION/bin/linux/amd64/kubectl  &&     chmod +x /usr/local/bin/kubectl
  | ---> Running in 182d2e39fca1
  |  
  | ---> 827f6771b448
  | Removing intermediate container 182d2e39fca1
  | Step 8/28 : ENV PYTHONUNBUFFERED 1 PYTHONIOENCODING UTF-8 LC_ALL en_US.UTF-8 LANG en_US.UTF-8 PIP_NO_CACHE_DIR off
  | ---> Running in 379ebed8e4c1
  | ---> 839b4d07bf5c
  | Removing intermediate container 379ebed8e4c1
  | Step 9/28 : RUN HOME=/opt/workshop &&     mkdir -p /opt/workshop &&     curl -s -o /tmp/get-pip.py https://bootstrap.pypa.io/get-pip.py  &&     /usr/bin/python /tmp/get-pip.py --user &&     rm -f /tmp/get-pip.py &&     $HOME/.local/bin/pip install --no-cache-dir --user virtualenv &&     $HOME/.local/bin/virtualenv /opt/workshop &&     source /opt/workshop/bin/activate &&     pip install supervisor==3.3.4 &&     mkdir -p /opt/app-root/etc &&     pip install butterfly==3.2.5 pygments==2.2.0 &&     curl -sL -o /tmp/asciidoc.tar.gz https://downloads.sourceforge.net/project/asciidoc/asciidoc/8.6.9/asciidoc-8.6.9.tar.gz  &&     tar -C /tmp -zxvf /tmp/asciidoc.tar.gz &&     (cd /tmp/asciidoc-8.6.9 &&     ./configure --prefix /opt/workshop &&     make install &&     cp asciidocapi.py /opt/workshop/lib/python2.7/site-packages) &&     rm -rf /tmp/asciidoc-8.6.9 /tmp/asciidoc.tar.gz &&     rm /opt/app-root/etc/scl_enable
  | ---> Running in f0acf2a50239
  |  
  | DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
  | Collecting pip
  | Downloading https://files.pythonhosted.org/packages/60/64/73b729587b6b0d13e690a7c3acd2231ee561e8dd28a58ae1b0409a5a2b20/pip-19.0-py2.py3-none-any.whl  (1.4MB)
  | Collecting setuptools
  | Downloading https://files.pythonhosted.org/packages/37/06/754589caf971b0d2d48f151c2586f62902d93dc908e2fd9b9b9f6aa3c9dd/setuptools-40.6.3-py2.py3-none-any.whl  (573kB)
  | Collecting wheel
  | Downloading https://files.pythonhosted.org/packages/ff/47/1dfa4795e24fd6f93d5d58602dd716c3f101cfd5a77cd9acbe519b44a0a9/wheel-0.32.3-py2.py3-none-any.whl
  | Exception:
  | Traceback (most recent call last):
  | File "/tmp/tmp8Q4GHF/pip.zip/pip/_internal/cli/base_command.py", line 176, in main
  | status = self.run(options, args)
  | File "/tmp/tmp8Q4GHF/pip.zip/pip/_internal/commands/install.py", line 346, in run
  | session=session, autobuilding=True
  | File "/tmp/tmp8Q4GHF/pip.zip/pip/_internal/wheel.py", line 848, in build
  | assert building_is_possible
  | AssertionError
  | Removing intermediate container f0acf2a50239
  | error: build error: The command '/bin/sh -c HOME=/opt/workshop &&     mkdir -p /opt/workshop &&     curl -s -o /tmp/get-pip.py https://bootstrap.pypa.io/get-pip.py  &&     /usr/bin/python /tmp/get-pip.py --user &&     rm -f /tmp/get-pip.py &&     $HOME/.local/bin/pip install --no-cache-dir --user virtualenv &&     $HOME/.local/bin/virtualenv /opt/workshop &&     source /opt/workshop/bin/activate &&     pip install supervisor==3.3.4 &&     mkdir -p /opt/app-root/etc &&     pip install butterfly==3.2.5 pygments==2.2.0 &&     curl -sL -o /tmp/asciidoc.tar.gz https://downloads.sourceforge.net/project/asciidoc/asciidoc/8.6.9/asciidoc-8.6.9.tar.gz  &&     tar -C /tmp -zxvf /tmp/asciidoc.tar.gz &&     (cd /tmp/asciidoc-8.6.9 &&     ./configure --prefix /opt/workshop &&     make install &&     cp asciidocapi.py /opt/workshop/lib/python2.7/site-packages) &&     rm -rf /tmp/asciidoc-8.6.9 /tmp/asciidoc.tar.gz &&     rm /opt/app-root/etc/scl_enable' returned a non-zero code: 2

Build logs from Terminal-hub-s2i-1
Cloning "https://github.com/jupyter-on-openshift/jupyterhub-quickstart.git " ...
	Commit:	bef4084ef5b3213a316a7520fc33ca5a27d7ec5c (Use APPLICATION_NAME environment variable, deprecating prior name.)
	Author:	Graham Dumpleton <Graham.Dumpleton@gmail.com>
	Date:	Thu Nov 8 15:01:07 2018 +1100
Using docker-registry.default.svc:5000/openshift/python@sha256:bc3538e03e4b8c60dbeb806e02b24360a389bd65a12ff73f55328eedfbcdcb3e as the s2i builder image
Collecting pip
Downloading https://files.pythonhosted.org/packages/60/64/73b729587b6b0d13e690a7c3acd2231ee561e8dd28a58ae1b0409a5a2b20/pip-19.0-py2.py3-none-any.whl  (1.4MB)
Collecting setuptools
Downloading https://files.pythonhosted.org/packages/37/06/754589caf971b0d2d48f151c2586f62902d93dc908e2fd9b9b9f6aa3c9dd/setuptools-40.6.3-py2.py3-none-any.whl  (573kB)
Collecting wheel
Downloading https://files.pythonhosted.org/packages/ff/47/1dfa4795e24fd6f93d5d58602dd716c3f101cfd5a77cd9acbe519b44a0a9/wheel-0.32.3-py2.py3-none-any.whl 
Installing collected packages: pip, setuptools, wheel
Found existing installation: pip 9.0.1
Uninstalling pip-9.0.1:
Successfully uninstalled pip-9.0.1
Found existing installation: setuptools 28.8.0
Uninstalling setuptools-28.8.0:
Successfully uninstalled setuptools-28.8.0
Found existing installation: wheel 0.29.0
Uninstalling wheel-0.29.0:
Successfully uninstalled wheel-0.29.0
Successfully installed pip-19.0 setuptools-40.6.3 wheel-0.32.3
Collecting git+https://github.com/jupyterhub/wrapspawner.git@5f2b7075f77d0c1c49066682a8e8adad0dab76db  (from -r /tmp/src/requirements.txt (line 3))
Cloning https://github.com/jupyterhub/wrapspawner.git  (to revision 5f2b7075f77d0c1c49066682a8e8adad0dab76db) to /tmp/pip-req-build-wcr23sqq
Collecting jupyterhub==0.9.4 (from -r /tmp/src/requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/23/7d/8f272ff69f05d51143e85753939884ca1e578639e273a8bfc1bda69f15bf/jupyterhub-0.9.4-py3-none-any.whl  (3.1MB)
Collecting jupyterhub-kubespawner==0.9.0 (from -r /tmp/src/requirements.txt (line 2))
Downloading https://files.pythonhosted.org/packages/44/c4/cc55963a68c17ce9771ec54615e1dae41f262d8f89340ec38d61a2b73443/jupyterhub_kubespawner-0.9.0-py3-none-any.whl 
Collecting jupyterhub-tmpauthenticator==0.5 (from -r /tmp/src/requirements.txt (line 4))
Downloading https://files.pythonhosted.org/packages/6f/a4/4b6275629fccf32efa038bee0616e9d48b02407517de64cd2470365926ed/jupyterhub_tmpauthenticator-0.5-py3-none-any.whl 
Collecting oauthenticator==0.8.0 (from -r /tmp/src/requirements.txt (line 5))
Downloading https://files.pythonhosted.org/packages/9d/60/cbe06e8e4113120e018b287ebb18d0c3c626e75fc1fa29e705fd7d4a0ce0/oauthenticator-0.8.0-py3-none-any.whl 
Collecting jupyterhub-ldapauthenticator==1.2.2 (from -r /tmp/src/requirements.txt (line 6))
Downloading https://files.pythonhosted.org/packages/d9/f6/a6ffa0b57ea08066d9ea52b64ad141866e984dd3ed5767c96e5eb51fc6a3/jupyterhub_ldapauthenticator-1.2.2-py3-none-any.whl 
Collecting psycopg2==2.7.5 (from -r /tmp/src/requirements.txt (line 7))
Downloading https://files.pythonhosted.org/packages/5e/d0/9e2b3ed43001ebed45caf56d5bb9d44ed3ebd68e12b87845bfa7bcd46250/psycopg2-2.7.5-cp36-cp36m-manylinux1_x86_64.whl  (2.7MB)
Collecting pamela (from jupyterhub==0.9.4->-r /tmp/src/requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/9c/b8/f7592a30aa95ffdea4f2e01aca87c15a7a315ba34f835235291eeba22779/pamela-1.0.0-py2.py3-none-any.whl 
Collecting python-oauth2>=1.0 (from jupyterhub==0.9.4->-r /tmp/src/requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/4c/a4/e92b8ba57ccfee230f196c80dc9327d1b626387c5ec1aa400e343161fde8/python-oauth2-1.1.0.tar.gz  (42kB)
Collecting python-dateutil (from jupyterhub==0.9.4->-r /tmp/src/requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/74/68/d87d9b36af36f44254a8d512cbfc48369103a3b9e474be9bdfe536abfc45/python_dateutil-2.7.5-py2.py3-none-any.whl  (225kB)
Collecting tornado>=5.0 (from jupyterhub==0.9.4->-r /tmp/src/requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/e6/78/6e7b5af12c12bdf38ca9bfe863fcaf53dc10430a312d0324e76c1e5ca426/tornado-5.1.1.tar.gz  (516kB)
Collecting SQLAlchemy>=1.1 (from jupyterhub==0.9.4->-r /tmp/src/requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/05/d2/17fb194f4ae83577258ea1d81da3d5d5643f4957fa14fd0261d78d648bf5/SQLAlchemy-1.2.16.tar.gz  (5.7MB)
Collecting requests (from jupyterhub==0.9.4->-r /tmp/src/requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl  (57kB)
Collecting jinja2 (from jupyterhub==0.9.4->-r /tmp/src/requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl  (126kB)
Collecting prometheus-client>=0.0.21 (from jupyterhub==0.9.4->-r /tmp/src/requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/bc/e1/3cddac03c8992815519c5f50493097f6508fa153d067b494db8ab5e9c4ce/prometheus_client-0.5.0.tar.gz 
Collecting alembic (from jupyterhub==0.9.4->-r /tmp/src/requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/50/7a/17bc17b3f5b01ebd3af38d71a15baa33beb241ab280b6ad0977ae24ec208/alembic-1.0.6.tar.gz  (1.0MB)
Collecting traitlets>=4.3.2 (from jupyterhub==0.9.4->-r /tmp/src/requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/93/d6/abcb22de61d78e2fc3959c964628a5771e47e7cc60d53e9342e21ed6cc9a/traitlets-4.3.2-py2.py3-none-any.whl  (74kB)
Collecting async-generator>=1.8 (from jupyterhub==0.9.4->-r /tmp/src/requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/71/52/39d20e03abd0ac9159c162ec24b93fbcaa111e8400308f2465432495ca2b/async_generator-1.10-py3-none-any.whl 
Collecting kubernetes==6.* (from jupyterhub-kubespawner==0.9.0->-r /tmp/src/requirements.txt (line 2))
Downloading https://files.pythonhosted.org/packages/0a/74/6de3a2bb2719f4514840cdde8d2190366433d32de9c46927b955dccbe402/kubernetes-6.1.0-py2.py3-none-any.whl  (1.2MB)
Collecting escapism (from jupyterhub-kubespawner==0.9.0->-r /tmp/src/requirements.txt (line 2))
Downloading https://files.pythonhosted.org/packages/d2/28/0f93611a7b8f50a5d22a576af9fe06af32abe5e2c47f09f64e39f8ea6dc3/escapism-1.0.0-py2.py3-none-any.whl 
Collecting pyYAML (from jupyterhub-kubespawner==0.9.0->-r /tmp/src/requirements.txt (line 2))
Downloading https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz  (270kB)
Collecting ldap3 (from jupyterhub-ldapauthenticator==1.2.2->-r /tmp/src/requirements.txt (line 6))
Downloading https://files.pythonhosted.org/packages/54/93/55d4de43abf3af1b60befa648811538b49701237e5cbda456608384b25ac/ldap3-2.5.2-py2.py3-none-any.whl  (393kB)
Collecting six>=1.5 (from python-dateutil->jupyterhub==0.9.4->-r /tmp/src/requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl 
Collecting urllib3<1.25,>=1.21.1 (from requests->jupyterhub==0.9.4->-r /tmp/src/requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl  (118kB)
Collecting idna<2.9,>=2.5 (from requests->jupyterhub==0.9.4->-r /tmp/src/requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl  (58kB)
Collecting chardet<3.1.0,>=3.0.2 (from requests->jupyterhub==0.9.4->-r /tmp/src/requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl  (133kB)
Collecting certifi>=2017.4.17 (from requests->jupyterhub==0.9.4->-r /tmp/src/requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl  (154kB)
Collecting MarkupSafe>=0.23 (from jinja2->jupyterhub==0.9.4->-r /tmp/src/requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/08/04/f2191b50fb7f0712f03f064b71d8b4605190f2178ba02e975a87f7b89a0d/MarkupSafe-1.1.0-cp36-cp36m-manylinux1_x86_64.whl 
Collecting Mako (from alembic->jupyterhub==0.9.4->-r /tmp/src/requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/eb/f3/67579bb486517c0d49547f9697e36582cd19dafb5df9e687ed8e22de57fa/Mako-1.0.7.tar.gz  (564kB)
Collecting python-editor>=0.3 (from alembic->jupyterhub==0.9.4->-r /tmp/src/requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/65/1e/adf6e000ea5dc909aa420352d6ba37f16434c8a3c2fa030445411a1ed545/python-editor-1.0.3.tar.gz 
Collecting decorator (from traitlets>=4.3.2->jupyterhub==0.9.4->-r /tmp/src/requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/bc/bb/a24838832ba35baf52f32ab1a49b906b5f82fb7c76b2f6a7e35e140bac30/decorator-4.3.0-py2.py3-none-any.whl 
Collecting ipython-genutils (from traitlets>=4.3.2->jupyterhub==0.9.4->-r /tmp/src/requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/fa/bc/9bd3b5c2b4774d5f33b2d544f1460be9df7df2fe42f352135381c347c69a/ipython_genutils-0.2.0-py2.py3-none-any.whl 
Collecting ipaddress>=1.0.17 (from kubernetes==6.*->jupyterhub-kubespawner==0.9.0->-r /tmp/src/requirements.txt (line 2))
Downloading https://files.pythonhosted.org/packages/fc/d0/7fc3a811e011d4b388be48a0e381db8d990042df54aa4ef4599a31d39853/ipaddress-1.0.22-py2.py3-none-any.whl 
Requirement already satisfied: setuptools>=21.0.0 in /opt/app-root/lib/python3.6/site-packages (from kubernetes==6.*->jupyterhub-kubespawner==0.9.0->-r /tmp/src/requirements.txt (line 2)) (40.6.3)
Collecting requests-oauthlib (from kubernetes==6.*->jupyterhub-kubespawner==0.9.0->-r /tmp/src/requirements.txt (line 2))
Downloading https://files.pythonhosted.org/packages/c2/e2/9fd03d55ffb70fe51f587f20bcf407a6927eb121de86928b34d162f0b1ac/requests_oauthlib-1.2.0-py2.py3-none-any.whl 
Collecting websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 (from kubernetes==6.*->jupyterhub-kubespawner==0.9.0->-r /tmp/src/requirements.txt (line 2))
Downloading https://files.pythonhosted.org/packages/26/2d/f749a5c82f6192d77ed061a38e02001afcba55fe8477336d26a950ab17ce/websocket_client-0.54.0-py2.py3-none-any.whl  (200kB)
Collecting google-auth>=1.0.1 (from kubernetes==6.*->jupyterhub-kubespawner==0.9.0->-r /tmp/src/requirements.txt (line 2))
Downloading https://files.pythonhosted.org/packages/4e/85/71b2dfbf5b4241cd031cc333ed71f90a271074a97cb2c517bb65f07a1a90/google_auth-1.6.2-py2.py3-none-any.whl  (73kB)
Collecting pyasn1>=0.1.8 (from ldap3->jupyterhub-ldapauthenticator==1.2.2->-r /tmp/src/requirements.txt (line 6))
Downloading https://files.pythonhosted.org/packages/7b/7c/c9386b82a25115cccf1903441bba3cbadcfae7b678a20167347fa8ded34c/pyasn1-0.4.5-py2.py3-none-any.whl  (73kB)
Collecting oauthlib>=3.0.0 (from requests-oauthlib->kubernetes==6.*->jupyterhub-kubespawner==0.9.0->-r /tmp/src/requirements.txt (line 2))
Downloading https://files.pythonhosted.org/packages/b8/03/ec2be6c125f330361afe33bff48ef7549c47da8fefc658a2df2242175b4b/oauthlib-3.0.0-py2.py3-none-any.whl  (142kB)
Collecting rsa>=3.1.4 (from google-auth>=1.0.1->kubernetes==6.*->jupyterhub-kubespawner==0.9.0->-r /tmp/src/requirements.txt (line 2))
Downloading https://files.pythonhosted.org/packages/02/e5/38518af393f7c214357079ce67a317307936896e961e35450b70fad2a9cf/rsa-4.0-py2.py3-none-any.whl 
Collecting pyasn1-modules>=0.2.1 (from google-auth>=1.0.1->kubernetes==6.*->jupyterhub-kubespawner==0.9.0->-r /tmp/src/requirements.txt (line 2))
Downloading https://files.pythonhosted.org/packages/59/84/339c2de112d7448d7d4c500b8016783d9eac8981f89ec1d58fdd4685d97f/pyasn1_modules-0.2.3-py2.py3-none-any.whl  (65kB)
Collecting cachetools>=2.0.0 (from google-auth>=1.0.1->kubernetes==6.*->jupyterhub-kubespawner==0.9.0->-r /tmp/src/requirements.txt (line 2))
Downloading https://files.pythonhosted.org/packages/76/7e/08cd3846bebeabb6b1cfc4af8aae649d90249b4aeed080bddb5297f1d73b/cachetools-3.0.0-py2.py3-none-any.whl 
Exception:
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 176, in main
    status = self.run(options, args)
  File "/opt/app-root/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 346, in run
    session=session, autobuilding=True
  File "/opt/app-root/lib/python3.6/site-packages/pip/_internal/wheel.py", line 848, in build
    assert building_is_possible
AssertionError
error: build error: non-zero (13) exit code from docker-registry.default.svc:5000/openshift/python@sha256:bc3538e03e4b8c60dbeb806e02b24360a389bd65a12ff73f55328eedfbcdcb3e

**Comment by jbrannst** [comment]
Duplicate of the redhat.registry.io issue
