### ISSUE TITLE
Configmap / application.properties is not being picked up Nationalparks.

### ISSUE THREAD

**Issue by alberttwong** [osevg/workshopper-content#22]
Works `oc set volumes dc/nationalparks --add -m /opt/openshift/config --configmap-name=nationalparks`

Works `oc env dc/nationalparks MONGODB_USER- MONGODB_PASSWORD- MONGODB_DATABASE- MONGODB_SERVER_HOST-`

looking at logs.... no more env variables.   I can shell into container at /opt/openshift/config with application.properties exists.    Application isn't picking up that it should see the new properties file in /opt/openshift/config and use those settings. 

```
Starting the Java application using /opt/run-java/run-java.sh ...
exec java -javaagent:/opt/jolokia/jolokia.jar=config=/opt/jolokia/etc/jolokia.properties -Xmx512m -XX:+UseParallelGC -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=100m -XX:ParallelGCThreads=4 -Djava.util.concurrent.ForkJoinPool.common.parallelism=4 -XX:CICompilerCount=2 -cp . -jar /deployments/nationalparks.jar
Picked up JAVA_TOOL_OPTIONS: -Duser.home=/home/jboss -Duser.name=jboss
I> No access restrictor found, access to any MBean is allowed
Jolokia: Agent started with URL https://10.1.4.50:8778/jolokia/
2017-03-24 02:25:59.160  INFO 1 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@4f47d241: startup date [Fri Mar 24 02:25:59 UTC 2017]; root of context hierarchy
2017-03-24 02:25:59.513  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'configurationPropertiesRebinderAutoConfiguration' of type [class org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$37c21e62] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.4.0.RELEASE)

2017-03-24 02:25:59.924  INFO 1 --- [           main] c.o.e.r.parks.NationalParksApplication   : No active profile set, falling back to default profiles: default
2017-03-24 02:25:59.944  INFO 1 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@35fb3008: startup date [Fri Mar 24 02:25:59 UTC 2017]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@4f47d241
2017-03-24 02:26:00.752  WARN 1 --- [           main] o.s.c.a.ConfigurationClassPostProcessor  : Cannot enhance @Configuration bean definition 'refreshScope' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static'.
2017-03-24 02:26:00.846  INFO 1 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=465a090f-c791-3081-ab41-945a326d52b2
2017-03-24 02:26:00.898  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [class org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$37c21e62] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-03-24 02:26:01.177  INFO 1 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8080 (http)
2017-03-24 02:26:01.189  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service Tomcat
2017-03-24 02:26:01.190  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.4
2017-03-24 02:26:01.286  INFO 1 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2017-03-24 02:26:01.286  INFO 1 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1342 ms
2017-03-24 02:26:01.411  INFO 1 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Mapping servlet: 'dispatcherServlet' to [/]
2017-03-24 02:26:01.414  INFO 1 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2017-03-24 02:26:01.414  INFO 1 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2017-03-24 02:26:01.415  INFO 1 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2017-03-24 02:26:01.415  INFO 1 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
[INFO] Connection string: mongodb://mongodb:mongodb@127.0.0.1:27017/mongodb
2017-03-24 02:26:01.536  INFO 1 --- [           main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[127.0.0.1:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2017-03-24 02:26:01.577  INFO 1 --- [127.0.0.1:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server 127.0.0.1:27017

com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.connection.SocketStream.open(SocketStream.java:63) ~[mongo-java-driver-3.3.0.jar!/:na]
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:115) ~[mongo-java-driver-3.3.0.jar!/:na]
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:116) ~[mongo-java-driver-3.3.0.jar!/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_121]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_121]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_121]
	at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:50) ~[mongo-java-driver-3.3.0.jar!/:na]
	at com.mongodb.connection.SocketStream.open(SocketStream.java:58) ~[mongo-java-driver-3.3.0.jar!/:na]
	... 3 common frames omitted

2017-03-24 02:26:02.015  INFO 1 --- [           main] s.w.s.m.m.a.RequestMappingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@35fb3008: startup date [Fri Mar 24 02:25:59 UTC 2017]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@4f47d241
2017-03-24 02:26:02.074  INFO 1 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/ws/info/],methods=[GET],produces=[application/json]}" onto public com.openshift.evg.roadshow.rest.gateway.model.Backend com.openshift.evg.roadshow.parks.rest.BackendController.get()
2017-03-24 02:26:02.075  INFO 1 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/ws/healthz/],methods=[GET]}" onto public java.lang.String com.openshift.evg.roadshow.parks.rest.Healthz.healthz()
2017-03-24 02:26:02.078  INFO 1 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/ws/data/centered],methods=[GET],produces=[application/json]}" onto public java.util.List<com.openshift.evg.roadshow.parks.model.Park> com.openshift.evg.roadshow.parks.rest.Parks.findParksCentered(float,float,int,int)
2017-03-24 02:26:02.080  INFO 1 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/ws/data/all],methods=[GET],produces=[application/json]}" onto public java.util.List<com.openshift.evg.roadshow.parks.model.Park> com.openshift.evg.roadshow.parks.rest.Parks.getAllParks()
2017-03-24 02:26:02.081  INFO 1 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/ws/data/within],methods=[GET],produces=[application/json]}" onto public java.util.List<com.openshift.evg.roadshow.parks.model.Park> com.openshift.evg.roadshow.parks.rest.Parks.findParksWithin(float,float,float,float)
2017-03-24 02:26:02.081  INFO 1 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/ws/data/load],methods=[GET],produces=[application/json]}" onto public java.lang.String com.openshift.evg.roadshow.parks.rest.Parks.load()
2017-03-24 02:26:02.083  INFO 1 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2017-03-24 02:26:02.084  INFO 1 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2017-03-24 02:26:02.106  INFO 1 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2017-03-24 02:26:02.106  INFO 1 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2017-03-24 02:26:02.136  INFO 1 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2017-03-24 02:26:02.267  INFO 1 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2017-03-24 02:26:02.276  INFO 1 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'configurationPropertiesRebinder' has been autodetected for JMX exposure
2017-03-24 02:26:02.277  INFO 1 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'refreshScope' has been autodetected for JMX exposure
2017-03-24 02:26:02.277  INFO 1 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'environmentManager' has been autodetected for JMX exposure
2017-03-24 02:26:02.279  INFO 1 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'environmentManager': registering with JMX server as MBean [org.springframework.cloud.context.environment:name=environmentManager,type=EnvironmentManager]
2017-03-24 02:26:02.291  INFO 1 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'refreshScope': registering with JMX server as MBean [org.springframework.cloud.context.scope.refresh:name=refreshScope,type=RefreshScope]
2017-03-24 02:26:02.300  INFO 1 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'configurationPropertiesRebinder': registering with JMX server as MBean [org.springframework.cloud.context.properties:name=configurationPropertiesRebinder,context=35fb3008,type=ConfigurationPropertiesRebinder]
2017-03-24 02:26:02.393  INFO 1 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8080 (http)
2017-03-24 02:26:02.397  INFO 1 --- [           main] c.o.e.r.parks.NationalParksApplication   : Started NationalParksApplication in 3.846 seconds (JVM running for 16.088)
2017-03-24 02:28:15.686  INFO 1 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring FrameworkServlet 'dispatcherServlet'
2017-03-24 02:28:15.687  INFO 1 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization started
2017-03-24 02:28:15.701  INFO 1 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 14 ms
[DEBUG] getAllParks
[DEBUG] MongoDBConnection.getAll()
2017-03-24 02:28:15.750  INFO 1 --- [nio-8080-exec-1] org.mongodb.driver.cluster               : No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, serverDescriptions=[ServerDescription{address=127.0.0.1:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]}. Waiting for 30000 ms before timing out
[ERROR] Error connecting to MongoDB. Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=127.0.0.1:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}] 
```

**Comment by alberttwong** [comment]
@jorgemoralespou I checked out your code.  I don't see how spring is looking for the /opt/openshift/config

**Comment by alberttwong** [comment]
I also created an OS environment variable with 

`JAVA_CLASSPATH="${CLASSPATH}:/opt/openshift/:/opt/openshift/config/"`

and I can see the logs that classpath is picked up but still, the spring code doesn't seem to load it. 

```
Starting the Java application using /opt/run-java/run-java.sh ...
exec java -javaagent:/opt/jolokia/jolokia.jar=config=/opt/jolokia/etc/jolokia.properties -Xmx512m -XX:+UseParallelGC -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=100m -XX:ParallelGCThreads=4 -Djava.util.concurrent.ForkJoinPool.common.parallelism=4 -XX:CICompilerCount=2 -cp "${CLASSPATH}:/opt/openshift/:/opt/openshift/config/" -jar /deployments/nationalparks.jar
```

**Comment by thoraxe** [comment]
This is a new problem that has suddenly cropped up. The nationalparks code hasn't changed in months, and this definitely worked when we did the roadshow in Irvine. I'm wondering if one of the dependencies has changed.

@jorgemoralespou 
@marekjelen 

Can either of you guys look into this? There are 3 events this week in Switzerland, including Zurich tomorrow.

**Comment by jorgemoralespou** [comment]
The image should be picking application.properties from the classpath, like documented here:
https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html

Also, using the fabric8 Kubernetes PropertySource should inject into the application anything in a config map with the same name as the application in a application.properties file, like documented here:
https://github.com/fabric8io/spring-cloud-kubernetes#kubernetes-propertysource

But then the pipeline is using profiles, dev and test.

I need to look into this with a lot of care about what the official image is doing. 

For now I have reverted the change in nationalparks to use old java-s2i (the one from jorgemoralespou) in branch 1.2.1 so if you use that branch while doing the labs, things should work with the unofficial image.

I'll look into this next week, as I can't look into this before now. Only thing I can do is just revert the change in branch 1.2.0 instead of 1.2.1 so there does not need to be any change in the content.

**Comment by jorgemoralespou** [comment]
You can set as JAVA_ARGS the location of the application.properties file, as it no longer is in the classpath with the new image.

![image](https://cloud.githubusercontent.com/assets/78350/24812164/4bbc053e-1bc9-11e7-8821-ba289b321bfc.png)

This will be needed before you unset the variables or as an additional to that same line

`````
oc env dc/nationalparks MONGODB_USER- MONGODB_PASSWORD- MONGODB_DATABASE- MONGODB_SERVER_HOST- JAVA_ARGS=--spring.config.location=file:/opt/openshift/config/application.properties
````

**Comment by thoraxe** [comment]
Is there no default classpath value for the location of this file?

**Comment by jorgemoralespou** [comment]
Couldn't  find it or make it work. I placed the file everywhere and this
was the only way to make it work.

**Comment by thoraxe** [comment]
OK. We'll have to rewrite the lab a little bit to make this work (tell the student to add the env var for the props file).

**Comment by jorgemoralespou** [comment]
That's in the branch I created.

https://github.com/osevg/workshopper-content/blob/1.3.0/configmap.adoc#L117-128
 (Lines 117 to 128)

2017-04-08 16:01 GMT+02:00 Erik M Jacobs <notifications@github.com>:

**Comment by jorgemoralespou** [comment]
Moved to /deployments/config and now the file is picked up
